# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'vcutter_menu.ui'
#
# Created: Fri Mar  9 09:22:05 2012
#      by: PyQt4 UI code generator 4.8.5
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(796, 393)
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.mainwidget = QtGui.QWidget(MainWindow)
        self.mainwidget.setObjectName(_fromUtf8("mainwidget"))
        self.header = QtGui.QLabel(self.mainwidget)
        self.header.setGeometry(QtCore.QRect(210, 10, 351, 20))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("DejaVu Sans"))
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.header.setFont(font)
        self.header.setText(QtGui.QApplication.translate("MainWindow", "            Video editing tool for Spoken Tutorials", None, QtGui.QApplication.UnicodeUTF8))
        self.header.setTextFormat(QtCore.Qt.RichText)
        self.header.setObjectName(_fromUtf8("header"))
        self.layoutWidget = QtGui.QWidget(self.mainwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(21, 60, 483, 26))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.convertthis = QtGui.QLabel(self.layoutWidget)
        self.convertthis.setText(QtGui.QApplication.translate("MainWindow", "1.  Convert this ", None, QtGui.QApplication.UnicodeUTF8))
        self.convertthis.setObjectName(_fromUtf8("convertthis"))
        self.horizontalLayout.addWidget(self.convertthis)
        self.video_1_1 = QtGui.QPushButton(self.layoutWidget)
        self.video_1_1.setText(QtGui.QApplication.translate("MainWindow", "video", None, QtGui.QApplication.UnicodeUTF8))
        self.video_1_1.setObjectName(_fromUtf8("video_1_1"))
        self.horizontalLayout.addWidget(self.video_1_1)
        self.intothis = QtGui.QLabel(self.layoutWidget)
        self.intothis.setText(QtGui.QApplication.translate("MainWindow", "into this ", None, QtGui.QApplication.UnicodeUTF8))
        self.intothis.setObjectName(_fromUtf8("intothis"))
        self.horizontalLayout.addWidget(self.intothis)
        self.vformat = QtGui.QComboBox(self.layoutWidget)
        self.vformat.setObjectName(_fromUtf8("vformat"))
        self.vformat.addItem(_fromUtf8(""))
        self.vformat.setItemText(0, QtGui.QApplication.translate("MainWindow", "format", None, QtGui.QApplication.UnicodeUTF8))
        self.vformat.addItem(_fromUtf8(""))
        self.vformat.setItemText(1, QtGui.QApplication.translate("MainWindow", "wmv", None, QtGui.QApplication.UnicodeUTF8))
        self.vformat.addItem(_fromUtf8(""))
        self.vformat.setItemText(2, QtGui.QApplication.translate("MainWindow", "mp4", None, QtGui.QApplication.UnicodeUTF8))
        self.horizontalLayout.addWidget(self.vformat)
        self.andkeepit = QtGui.QLabel(self.layoutWidget)
        self.andkeepit.setText(QtGui.QApplication.translate("MainWindow", "and keep it", None, QtGui.QApplication.UnicodeUTF8))
        self.andkeepit.setObjectName(_fromUtf8("andkeepit"))
        self.horizontalLayout.addWidget(self.andkeepit)
        self.here_1 = QtGui.QPushButton(self.layoutWidget)
        self.here_1.setText(QtGui.QApplication.translate("MainWindow", "here", None, QtGui.QApplication.UnicodeUTF8))
        self.here_1.setObjectName(_fromUtf8("here_1"))
        self.horizontalLayout.addWidget(self.here_1)
        self.execute1 = QtGui.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.execute1.setFont(font)
        self.execute1.setAutoFillBackground(False)
        self.execute1.setText(QtGui.QApplication.translate("MainWindow", "execute", None, QtGui.QApplication.UnicodeUTF8))
        self.execute1.setObjectName(_fromUtf8("execute1"))
        self.horizontalLayout.addWidget(self.execute1)
        self.layoutWidget1 = QtGui.QWidget(self.mainwidget)
        self.layoutWidget1.setGeometry(QtCore.QRect(21, 110, 562, 26))
        self.layoutWidget1.setObjectName(_fromUtf8("layoutWidget1"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_2.setMargin(0)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.addthis = QtGui.QLabel(self.layoutWidget1)
        self.addthis.setText(QtGui.QApplication.translate("MainWindow", "2.  Add this ", None, QtGui.QApplication.UnicodeUTF8))
        self.addthis.setObjectName(_fromUtf8("addthis"))
        self.horizontalLayout_2.addWidget(self.addthis)
        self.video_2_1 = QtGui.QPushButton(self.layoutWidget1)
        self.video_2_1.setText(QtGui.QApplication.translate("MainWindow", "video", None, QtGui.QApplication.UnicodeUTF8))
        self.video_2_1.setObjectName(_fromUtf8("video_2_1"))
        self.horizontalLayout_2.addWidget(self.video_2_1)
        self.atthe = QtGui.QLabel(self.layoutWidget1)
        self.atthe.setText(QtGui.QApplication.translate("MainWindow", "at the ", None, QtGui.QApplication.UnicodeUTF8))
        self.atthe.setObjectName(_fromUtf8("atthe"))
        self.horizontalLayout_2.addWidget(self.atthe)
        self.end = QtGui.QComboBox(self.layoutWidget1)
        self.end.setObjectName(_fromUtf8("end"))
        self.end.addItem(_fromUtf8(""))
        self.end.setItemText(0, QtGui.QApplication.translate("MainWindow", "select", None, QtGui.QApplication.UnicodeUTF8))
        self.end.addItem(_fromUtf8(""))
        self.end.setItemText(1, QtGui.QApplication.translate("MainWindow", "end", None, QtGui.QApplication.UnicodeUTF8))
        self.end.addItem(_fromUtf8(""))
        self.end.setItemText(2, QtGui.QApplication.translate("MainWindow", "beginning", None, QtGui.QApplication.UnicodeUTF8))
        self.horizontalLayout_2.addWidget(self.end)
        self.ofthis = QtGui.QLabel(self.layoutWidget1)
        self.ofthis.setText(QtGui.QApplication.translate("MainWindow", "of this", None, QtGui.QApplication.UnicodeUTF8))
        self.ofthis.setObjectName(_fromUtf8("ofthis"))
        self.horizontalLayout_2.addWidget(self.ofthis)
        self.video_2_2 = QtGui.QPushButton(self.layoutWidget1)
        self.video_2_2.setText(QtGui.QApplication.translate("MainWindow", "video", None, QtGui.QApplication.UnicodeUTF8))
        self.video_2_2.setObjectName(_fromUtf8("video_2_2"))
        self.horizontalLayout_2.addWidget(self.video_2_2)
        self.andkeepit_2 = QtGui.QLabel(self.layoutWidget1)
        self.andkeepit_2.setText(QtGui.QApplication.translate("MainWindow", "and keep it", None, QtGui.QApplication.UnicodeUTF8))
        self.andkeepit_2.setObjectName(_fromUtf8("andkeepit_2"))
        self.horizontalLayout_2.addWidget(self.andkeepit_2)
        self.here_2 = QtGui.QPushButton(self.layoutWidget1)
        self.here_2.setText(QtGui.QApplication.translate("MainWindow", "here", None, QtGui.QApplication.UnicodeUTF8))
        self.here_2.setObjectName(_fromUtf8("here_2"))
        self.horizontalLayout_2.addWidget(self.here_2)
        self.execute2 = QtGui.QPushButton(self.layoutWidget1)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.execute2.setFont(font)
        self.execute2.setAutoFillBackground(False)
        self.execute2.setText(QtGui.QApplication.translate("MainWindow", "execute", None, QtGui.QApplication.UnicodeUTF8))
        self.execute2.setObjectName(_fromUtf8("execute2"))
        self.horizontalLayout_2.addWidget(self.execute2)
        self.footer = QtGui.QLabel(self.mainwidget)
        self.footer.setGeometry(QtCore.QRect(10, 350, 781, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setItalic(False)
        font.setUnderline(True)
        self.footer.setFont(font)
        self.footer.setText(QtGui.QApplication.translate("MainWindow", "Will add progress bar soon. Download the latest version from github.com/srikantpatnaik/vCutter, please suggest more editing options at srikant@fossee.in", None, QtGui.QApplication.UnicodeUTF8))
        self.footer.setObjectName(_fromUtf8("footer"))
        self.widget = QtGui.QWidget(self.mainwidget)
        self.widget.setGeometry(QtCore.QRect(20, 160, 751, 26))
        self.widget.setObjectName(_fromUtf8("widget"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.widget)
        self.horizontalLayout_3.setMargin(0)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.cutthis = QtGui.QLabel(self.widget)
        self.cutthis.setText(QtGui.QApplication.translate("MainWindow", "3.  Cut this ", None, QtGui.QApplication.UnicodeUTF8))
        self.cutthis.setObjectName(_fromUtf8("cutthis"))
        self.horizontalLayout_3.addWidget(self.cutthis)
        self.video_3_1 = QtGui.QPushButton(self.widget)
        self.video_3_1.setText(QtGui.QApplication.translate("MainWindow", "video", None, QtGui.QApplication.UnicodeUTF8))
        self.video_3_1.setObjectName(_fromUtf8("video_3_1"))
        self.horizontalLayout_3.addWidget(self.video_3_1)
        self.from_text = QtGui.QLabel(self.widget)
        self.from_text.setText(QtGui.QApplication.translate("MainWindow", "from", None, QtGui.QApplication.UnicodeUTF8))
        self.from_text.setObjectName(_fromUtf8("from_text"))
        self.horizontalLayout_3.addWidget(self.from_text)
        self.time_from = QtGui.QLineEdit(self.widget)
        self.time_from.setObjectName(_fromUtf8("time_from"))
        self.horizontalLayout_3.addWidget(self.time_from)
        self.to_text = QtGui.QLabel(self.widget)
        self.to_text.setText(QtGui.QApplication.translate("MainWindow", "to", None, QtGui.QApplication.UnicodeUTF8))
        self.to_text.setObjectName(_fromUtf8("to_text"))
        self.horizontalLayout_3.addWidget(self.to_text)
        self.time_to = QtGui.QLineEdit(self.widget)
        self.time_to.setObjectName(_fromUtf8("time_to"))
        self.horizontalLayout_3.addWidget(self.time_to)
        self.andinsertthis = QtGui.QLabel(self.widget)
        self.andinsertthis.setText(QtGui.QApplication.translate("MainWindow", "& insert this", None, QtGui.QApplication.UnicodeUTF8))
        self.andinsertthis.setObjectName(_fromUtf8("andinsertthis"))
        self.horizontalLayout_3.addWidget(self.andinsertthis)
        self.videoclip = QtGui.QPushButton(self.widget)
        self.videoclip.setText(QtGui.QApplication.translate("MainWindow", "video clip", None, QtGui.QApplication.UnicodeUTF8))
        self.videoclip.setObjectName(_fromUtf8("videoclip"))
        self.horizontalLayout_3.addWidget(self.videoclip)
        self.inplaceofit = QtGui.QLabel(self.widget)
        self.inplaceofit.setText(QtGui.QApplication.translate("MainWindow", "in place of it, stich them & save it", None, QtGui.QApplication.UnicodeUTF8))
        self.inplaceofit.setObjectName(_fromUtf8("inplaceofit"))
        self.horizontalLayout_3.addWidget(self.inplaceofit)
        self.here_3 = QtGui.QPushButton(self.widget)
        self.here_3.setText(QtGui.QApplication.translate("MainWindow", "here", None, QtGui.QApplication.UnicodeUTF8))
        self.here_3.setObjectName(_fromUtf8("here_3"))
        self.horizontalLayout_3.addWidget(self.here_3)
        self.execute3 = QtGui.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.execute3.setFont(font)
        self.execute3.setAutoFillBackground(False)
        self.execute3.setText(QtGui.QApplication.translate("MainWindow", "execute", None, QtGui.QApplication.UnicodeUTF8))
        self.execute3.setObjectName(_fromUtf8("execute3"))
        self.horizontalLayout_3.addWidget(self.execute3)
        self.widget1 = QtGui.QWidget(self.mainwidget)
        self.widget1.setGeometry(QtCore.QRect(21, 210, 737, 26))
        self.widget1.setObjectName(_fromUtf8("widget1"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.widget1)
        self.horizontalLayout_4.setMargin(0)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.cutthis_4 = QtGui.QLabel(self.widget1)
        self.cutthis_4.setText(QtGui.QApplication.translate("MainWindow", "4.  Cut this ", None, QtGui.QApplication.UnicodeUTF8))
        self.cutthis_4.setObjectName(_fromUtf8("cutthis_4"))
        self.horizontalLayout_4.addWidget(self.cutthis_4)
        self.video_4_1 = QtGui.QPushButton(self.widget1)
        self.video_4_1.setText(QtGui.QApplication.translate("MainWindow", "video", None, QtGui.QApplication.UnicodeUTF8))
        self.video_4_1.setObjectName(_fromUtf8("video_4_1"))
        self.horizontalLayout_4.addWidget(self.video_4_1)
        self.from_text_4 = QtGui.QLabel(self.widget1)
        self.from_text_4.setText(QtGui.QApplication.translate("MainWindow", "from", None, QtGui.QApplication.UnicodeUTF8))
        self.from_text_4.setObjectName(_fromUtf8("from_text_4"))
        self.horizontalLayout_4.addWidget(self.from_text_4)
        self.time_from_4 = QtGui.QLineEdit(self.widget1)
        self.time_from_4.setObjectName(_fromUtf8("time_from_4"))
        self.horizontalLayout_4.addWidget(self.time_from_4)
        self.to_text_2 = QtGui.QLabel(self.widget1)
        self.to_text_2.setText(QtGui.QApplication.translate("MainWindow", "to", None, QtGui.QApplication.UnicodeUTF8))
        self.to_text_2.setObjectName(_fromUtf8("to_text_2"))
        self.horizontalLayout_4.addWidget(self.to_text_2)
        self.time_to_4 = QtGui.QLineEdit(self.widget1)
        self.time_to_4.setObjectName(_fromUtf8("time_to_4"))
        self.horizontalLayout_4.addWidget(self.time_to_4)
        self.stichback_4 = QtGui.QLabel(self.widget1)
        self.stichback_4.setText(QtGui.QApplication.translate("MainWindow", "and remove the region then stich back the original video", None, QtGui.QApplication.UnicodeUTF8))
        self.stichback_4.setObjectName(_fromUtf8("stichback_4"))
        self.horizontalLayout_4.addWidget(self.stichback_4)
        self.here_4 = QtGui.QPushButton(self.widget1)
        self.here_4.setText(QtGui.QApplication.translate("MainWindow", "here", None, QtGui.QApplication.UnicodeUTF8))
        self.here_4.setObjectName(_fromUtf8("here_4"))
        self.horizontalLayout_4.addWidget(self.here_4)
        self.execute4 = QtGui.QPushButton(self.widget1)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.execute4.setFont(font)
        self.execute4.setAutoFillBackground(False)
        self.execute4.setText(QtGui.QApplication.translate("MainWindow", "execute", None, QtGui.QApplication.UnicodeUTF8))
        self.execute4.setObjectName(_fromUtf8("execute4"))
        self.horizontalLayout_4.addWidget(self.execute4)
        self.widget2 = QtGui.QWidget(self.mainwidget)
        self.widget2.setGeometry(QtCore.QRect(21, 260, 541, 26))
        self.widget2.setObjectName(_fromUtf8("widget2"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.widget2)
        self.horizontalLayout_5.setMargin(0)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.cutthis_5 = QtGui.QLabel(self.widget2)
        self.cutthis_5.setText(QtGui.QApplication.translate("MainWindow", "5.  Cut this ", None, QtGui.QApplication.UnicodeUTF8))
        self.cutthis_5.setObjectName(_fromUtf8("cutthis_5"))
        self.horizontalLayout_5.addWidget(self.cutthis_5)
        self.video_5_1 = QtGui.QPushButton(self.widget2)
        self.video_5_1.setText(QtGui.QApplication.translate("MainWindow", "video", None, QtGui.QApplication.UnicodeUTF8))
        self.video_5_1.setObjectName(_fromUtf8("video_5_1"))
        self.horizontalLayout_5.addWidget(self.video_5_1)
        self.from_text_5 = QtGui.QLabel(self.widget2)
        self.from_text_5.setText(QtGui.QApplication.translate("MainWindow", "from", None, QtGui.QApplication.UnicodeUTF8))
        self.from_text_5.setObjectName(_fromUtf8("from_text_5"))
        self.horizontalLayout_5.addWidget(self.from_text_5)
        self.time_from_5 = QtGui.QLineEdit(self.widget2)
        self.time_from_5.setObjectName(_fromUtf8("time_from_5"))
        self.horizontalLayout_5.addWidget(self.time_from_5)
        self.to_text_3 = QtGui.QLabel(self.widget2)
        self.to_text_3.setText(QtGui.QApplication.translate("MainWindow", "to", None, QtGui.QApplication.UnicodeUTF8))
        self.to_text_3.setObjectName(_fromUtf8("to_text_3"))
        self.horizontalLayout_5.addWidget(self.to_text_3)
        self.time_to_5 = QtGui.QLineEdit(self.widget2)
        self.time_to_5.setObjectName(_fromUtf8("time_to_5"))
        self.horizontalLayout_5.addWidget(self.time_to_5)
        self.savethecut = QtGui.QLabel(self.widget2)
        self.savethecut.setText(QtGui.QApplication.translate("MainWindow", "& save the cut portion", None, QtGui.QApplication.UnicodeUTF8))
        self.savethecut.setObjectName(_fromUtf8("savethecut"))
        self.horizontalLayout_5.addWidget(self.savethecut)
        self.here_5 = QtGui.QPushButton(self.widget2)
        self.here_5.setText(QtGui.QApplication.translate("MainWindow", "here", None, QtGui.QApplication.UnicodeUTF8))
        self.here_5.setObjectName(_fromUtf8("here_5"))
        self.horizontalLayout_5.addWidget(self.here_5)
        self.execute5 = QtGui.QPushButton(self.widget2)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.execute5.setFont(font)
        self.execute5.setAutoFillBackground(False)
        self.execute5.setText(QtGui.QApplication.translate("MainWindow", "execute", None, QtGui.QApplication.UnicodeUTF8))
        self.execute5.setObjectName(_fromUtf8("execute5"))
        self.horizontalLayout_5.addWidget(self.execute5)
        MainWindow.setCentralWidget(self.mainwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 796, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setTitle(QtGui.QApplication.translate("MainWindow", "&File", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menu_Help = QtGui.QMenu(self.menubar)
        self.menu_Help.setTitle(QtGui.QApplication.translate("MainWindow", "&Help", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_Help.setObjectName(_fromUtf8("menu_Help"))
        MainWindow.setMenuBar(self.menubar)
        self.actionQuit = QtGui.QAction(MainWindow)
        self.actionQuit.setText(QtGui.QApplication.translate("MainWindow", "&Quit", None, QtGui.QApplication.UnicodeUTF8))
        self.actionQuit.setObjectName(_fromUtf8("actionQuit"))
        self.action_About = QtGui.QAction(MainWindow)
        self.action_About.setText(QtGui.QApplication.translate("MainWindow", "&About", None, QtGui.QApplication.UnicodeUTF8))
        self.action_About.setObjectName(_fromUtf8("action_About"))
        self.menuFile.addAction(self.actionQuit)
        self.menu_Help.addAction(self.action_About)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menu_Help.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QObject.connect(self.actionQuit, QtCore.SIGNAL(_fromUtf8("activated()")), MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        pass


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

