# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'vcutter_menu.ui'
#
# Created: Tue Mar  6 17:47:52 2012
#      by: PyQt4 UI code generator 4.8.5
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(696, 297)
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.mainwidget = QtGui.QWidget(MainWindow)
        self.mainwidget.setObjectName(_fromUtf8("mainwidget"))
        self.header = QtGui.QLabel(self.mainwidget)
        self.header.setGeometry(QtCore.QRect(140, 10, 391, 20))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Ubuntu"))
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.header.setFont(font)
        self.header.setText(QtGui.QApplication.translate("MainWindow", "  Video editing application tailored for Spoken Tutorials", None, QtGui.QApplication.UnicodeUTF8))
        self.header.setTextFormat(QtCore.Qt.RichText)
        self.header.setObjectName(_fromUtf8("header"))
        self.execute = QtGui.QPushButton(self.mainwidget)
        self.execute.setGeometry(QtCore.QRect(20, 210, 141, 41))
        self.execute.setText(QtGui.QApplication.translate("MainWindow", "execute", None, QtGui.QApplication.UnicodeUTF8))
        self.execute.setObjectName(_fromUtf8("execute"))
        self.layoutWidget = QtGui.QWidget(self.mainwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 60, 436, 26))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.one = QtGui.QRadioButton(self.layoutWidget)
        self.one.setText(_fromUtf8(""))
        self.one.setObjectName(_fromUtf8("one"))
        self.horizontalLayout.addWidget(self.one)
        self.convertthis = QtGui.QLabel(self.layoutWidget)
        self.convertthis.setText(QtGui.QApplication.translate("MainWindow", "1.  Convert this ", None, QtGui.QApplication.UnicodeUTF8))
        self.convertthis.setObjectName(_fromUtf8("convertthis"))
        self.horizontalLayout.addWidget(self.convertthis)
        self.video_1_1 = QtGui.QPushButton(self.layoutWidget)
        self.video_1_1.setText(QtGui.QApplication.translate("MainWindow", "video", None, QtGui.QApplication.UnicodeUTF8))
        self.video_1_1.setObjectName(_fromUtf8("video_1_1"))
        self.horizontalLayout.addWidget(self.video_1_1)
        self.intothis = QtGui.QLabel(self.layoutWidget)
        self.intothis.setText(QtGui.QApplication.translate("MainWindow", "into this ", None, QtGui.QApplication.UnicodeUTF8))
        self.intothis.setObjectName(_fromUtf8("intothis"))
        self.horizontalLayout.addWidget(self.intothis)
        self.vformat = QtGui.QComboBox(self.layoutWidget)
        self.vformat.setObjectName(_fromUtf8("vformat"))
        self.vformat.addItem(_fromUtf8(""))
        self.vformat.setItemText(0, QtGui.QApplication.translate("MainWindow", "format", None, QtGui.QApplication.UnicodeUTF8))
        self.vformat.addItem(_fromUtf8(""))
        self.vformat.setItemText(1, QtGui.QApplication.translate("MainWindow", "wmv", None, QtGui.QApplication.UnicodeUTF8))
        self.vformat.addItem(_fromUtf8(""))
        self.vformat.setItemText(2, QtGui.QApplication.translate("MainWindow", "3gp", None, QtGui.QApplication.UnicodeUTF8))
        self.vformat.addItem(_fromUtf8(""))
        self.vformat.setItemText(3, QtGui.QApplication.translate("MainWindow", "mp4", None, QtGui.QApplication.UnicodeUTF8))
        self.vformat.addItem(_fromUtf8(""))
        self.vformat.setItemText(4, QtGui.QApplication.translate("MainWindow", "avi", None, QtGui.QApplication.UnicodeUTF8))
        self.horizontalLayout.addWidget(self.vformat)
        self.andkeepit = QtGui.QLabel(self.layoutWidget)
        self.andkeepit.setText(QtGui.QApplication.translate("MainWindow", "and keep it", None, QtGui.QApplication.UnicodeUTF8))
        self.andkeepit.setObjectName(_fromUtf8("andkeepit"))
        self.horizontalLayout.addWidget(self.andkeepit)
        self.here_1 = QtGui.QPushButton(self.layoutWidget)
        self.here_1.setText(QtGui.QApplication.translate("MainWindow", "here", None, QtGui.QApplication.UnicodeUTF8))
        self.here_1.setObjectName(_fromUtf8("here_1"))
        self.horizontalLayout.addWidget(self.here_1)
        self.layoutWidget1 = QtGui.QWidget(self.mainwidget)
        self.layoutWidget1.setGeometry(QtCore.QRect(20, 110, 514, 26))
        self.layoutWidget1.setObjectName(_fromUtf8("layoutWidget1"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_2.setMargin(0)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.two = QtGui.QRadioButton(self.layoutWidget1)
        self.two.setText(_fromUtf8(""))
        self.two.setObjectName(_fromUtf8("two"))
        self.horizontalLayout_2.addWidget(self.two)
        self.addthis = QtGui.QLabel(self.layoutWidget1)
        self.addthis.setText(QtGui.QApplication.translate("MainWindow", "2.  Add this ", None, QtGui.QApplication.UnicodeUTF8))
        self.addthis.setObjectName(_fromUtf8("addthis"))
        self.horizontalLayout_2.addWidget(self.addthis)
        self.video_2_1 = QtGui.QPushButton(self.layoutWidget1)
        self.video_2_1.setText(QtGui.QApplication.translate("MainWindow", "video", None, QtGui.QApplication.UnicodeUTF8))
        self.video_2_1.setObjectName(_fromUtf8("video_2_1"))
        self.horizontalLayout_2.addWidget(self.video_2_1)
        self.atthe = QtGui.QLabel(self.layoutWidget1)
        self.atthe.setText(QtGui.QApplication.translate("MainWindow", "at the ", None, QtGui.QApplication.UnicodeUTF8))
        self.atthe.setObjectName(_fromUtf8("atthe"))
        self.horizontalLayout_2.addWidget(self.atthe)
        self.end = QtGui.QComboBox(self.layoutWidget1)
        self.end.setObjectName(_fromUtf8("end"))
        self.end.addItem(_fromUtf8(""))
        self.end.setItemText(0, QtGui.QApplication.translate("MainWindow", "end", None, QtGui.QApplication.UnicodeUTF8))
        self.end.addItem(_fromUtf8(""))
        self.end.setItemText(1, QtGui.QApplication.translate("MainWindow", "beginning", None, QtGui.QApplication.UnicodeUTF8))
        self.horizontalLayout_2.addWidget(self.end)
        self.ofthis = QtGui.QLabel(self.layoutWidget1)
        self.ofthis.setText(QtGui.QApplication.translate("MainWindow", "of this", None, QtGui.QApplication.UnicodeUTF8))
        self.ofthis.setObjectName(_fromUtf8("ofthis"))
        self.horizontalLayout_2.addWidget(self.ofthis)
        self.video_2_2 = QtGui.QPushButton(self.layoutWidget1)
        self.video_2_2.setText(QtGui.QApplication.translate("MainWindow", "video", None, QtGui.QApplication.UnicodeUTF8))
        self.video_2_2.setObjectName(_fromUtf8("video_2_2"))
        self.horizontalLayout_2.addWidget(self.video_2_2)
        self.andkeepit_2 = QtGui.QLabel(self.layoutWidget1)
        self.andkeepit_2.setText(QtGui.QApplication.translate("MainWindow", "and keep it", None, QtGui.QApplication.UnicodeUTF8))
        self.andkeepit_2.setObjectName(_fromUtf8("andkeepit_2"))
        self.horizontalLayout_2.addWidget(self.andkeepit_2)
        self.here_2 = QtGui.QPushButton(self.layoutWidget1)
        self.here_2.setText(QtGui.QApplication.translate("MainWindow", "here", None, QtGui.QApplication.UnicodeUTF8))
        self.here_2.setObjectName(_fromUtf8("here_2"))
        self.horizontalLayout_2.addWidget(self.here_2)
        self.layoutWidget2 = QtGui.QWidget(self.mainwidget)
        self.layoutWidget2.setGeometry(QtCore.QRect(21, 161, 640, 26))
        self.layoutWidget2.setObjectName(_fromUtf8("layoutWidget2"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.layoutWidget2)
        self.horizontalLayout_3.setMargin(0)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.three = QtGui.QRadioButton(self.layoutWidget2)
        self.three.setText(_fromUtf8(""))
        self.three.setObjectName(_fromUtf8("three"))
        self.horizontalLayout_3.addWidget(self.three)
        self.cutthis = QtGui.QLabel(self.layoutWidget2)
        self.cutthis.setText(QtGui.QApplication.translate("MainWindow", "3.  Cut this ", None, QtGui.QApplication.UnicodeUTF8))
        self.cutthis.setObjectName(_fromUtf8("cutthis"))
        self.horizontalLayout_3.addWidget(self.cutthis)
        self.video_3_1 = QtGui.QPushButton(self.layoutWidget2)
        self.video_3_1.setText(QtGui.QApplication.translate("MainWindow", "video", None, QtGui.QApplication.UnicodeUTF8))
        self.video_3_1.setObjectName(_fromUtf8("video_3_1"))
        self.horizontalLayout_3.addWidget(self.video_3_1)
        self.from_text = QtGui.QLabel(self.layoutWidget2)
        self.from_text.setText(QtGui.QApplication.translate("MainWindow", "from", None, QtGui.QApplication.UnicodeUTF8))
        self.from_text.setObjectName(_fromUtf8("from_text"))
        self.horizontalLayout_3.addWidget(self.from_text)
        self.from_time = QtGui.QDoubleSpinBox(self.layoutWidget2)
        self.from_time.setObjectName(_fromUtf8("from_time"))
        self.horizontalLayout_3.addWidget(self.from_time)
        self.to_text = QtGui.QLabel(self.layoutWidget2)
        self.to_text.setText(QtGui.QApplication.translate("MainWindow", "to", None, QtGui.QApplication.UnicodeUTF8))
        self.to_text.setObjectName(_fromUtf8("to_text"))
        self.horizontalLayout_3.addWidget(self.to_text)
        self.to_2 = QtGui.QDoubleSpinBox(self.layoutWidget2)
        self.to_2.setObjectName(_fromUtf8("to_2"))
        self.horizontalLayout_3.addWidget(self.to_2)
        self.andinsertthis = QtGui.QLabel(self.layoutWidget2)
        self.andinsertthis.setText(QtGui.QApplication.translate("MainWindow", "& insert this", None, QtGui.QApplication.UnicodeUTF8))
        self.andinsertthis.setObjectName(_fromUtf8("andinsertthis"))
        self.horizontalLayout_3.addWidget(self.andinsertthis)
        self.videoclip = QtGui.QPushButton(self.layoutWidget2)
        self.videoclip.setText(QtGui.QApplication.translate("MainWindow", "video clip", None, QtGui.QApplication.UnicodeUTF8))
        self.videoclip.setObjectName(_fromUtf8("videoclip"))
        self.horizontalLayout_3.addWidget(self.videoclip)
        self.inplaceofit = QtGui.QLabel(self.layoutWidget2)
        self.inplaceofit.setText(QtGui.QApplication.translate("MainWindow", "in place of it, join", None, QtGui.QApplication.UnicodeUTF8))
        self.inplaceofit.setObjectName(_fromUtf8("inplaceofit"))
        self.horizontalLayout_3.addWidget(self.inplaceofit)
        self.here_3 = QtGui.QPushButton(self.layoutWidget2)
        self.here_3.setText(QtGui.QApplication.translate("MainWindow", "here", None, QtGui.QApplication.UnicodeUTF8))
        self.here_3.setObjectName(_fromUtf8("here_3"))
        self.horizontalLayout_3.addWidget(self.here_3)
        MainWindow.setCentralWidget(self.mainwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 696, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setTitle(QtGui.QApplication.translate("MainWindow", "&File", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menu_Help = QtGui.QMenu(self.menubar)
        self.menu_Help.setTitle(QtGui.QApplication.translate("MainWindow", "&Help", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_Help.setObjectName(_fromUtf8("menu_Help"))
        MainWindow.setMenuBar(self.menubar)
        self.actionQuit = QtGui.QAction(MainWindow)
        self.actionQuit.setText(QtGui.QApplication.translate("MainWindow", "&Quit", None, QtGui.QApplication.UnicodeUTF8))
        self.actionQuit.setObjectName(_fromUtf8("actionQuit"))
        self.action_About = QtGui.QAction(MainWindow)
        self.action_About.setText(QtGui.QApplication.translate("MainWindow", "&About", None, QtGui.QApplication.UnicodeUTF8))
        self.action_About.setObjectName(_fromUtf8("action_About"))
        self.menuFile.addAction(self.actionQuit)
        self.menu_Help.addAction(self.action_About)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menu_Help.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QObject.connect(self.actionQuit, QtCore.SIGNAL(_fromUtf8("activated()")), MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        pass


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

